### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [dcousin3/CohensdpLibrary#1]
I suggest adding the topics `statistics`, `r` in the about section at https://github.com/dcousin3/CohensdpLibrary

**Comment by dcousin3** [comment]
Thanks for the suggestion!

**Comment by Beliavsky** [comment]
The suggestion is to classify the repo with searchable topics, as described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by dcousin3** [comment]
Got it!
